<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MAE</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>amirsafwan23@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0f6d4b02-7f29-4cdc-b1a8-04753e23de11</testSuiteGuid>
   <testCaseLink>
      <guid>26d8f510-2057-4099-b3dd-ee22d092b773</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login Onboard/onboard_onboardIntoMAE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514189f4-0f50-4fc5-8f87-6b6e5311aa3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d62a261-211f-48ea-9b7d-0b01f111d556</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c15756f8-dfa2-422d-913f-18401db54c80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Settings/settings_secure2uRegistration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc5f1bf-e970-49a6-9ead-df2e6654e9b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df591683-93d7-456f-8377-a4a967fcc440</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PayBill/payBills_todayTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>576c3488-6fca-4dc6-a127-67f5d4b1609c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PayBill/payBills_Future Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ef0f2f6-dbff-4f98-a730-194addd0cf22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_todayTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d30065c-b90f-4a7d-b953-bb741d29675a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>031d3bff-0913-4a21-8135-d5499122af4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ea246c7-5acd-49ca-b0f8-a412fd03e158</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Add Favorite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffa9e35a-32d2-431f-ac14-5a4308848fc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Favorite Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0cc8b16-128d-42aa-9f1a-24adfd0bef6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ca9d1b-9824-4a5b-8c6d-2dc34c246ae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f1adceb-72f1-4e2a-9621-9d085c4ad0f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_Future Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb186dac-eee1-40a4-ac6f-f6a665d21e7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85768c90-7b48-42d3-b18c-4783961a788b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1c84b7c-253b-40af-8d7d-28978a4a08c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59253758-72d7-485e-8a66-86c45bad11d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPaymentAddFavorite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e92331a-446b-46a7-811f-ce65d357bda6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9f0f880-3cf9-4bfb-b689-bba6176de99f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3f3b4b7-84ee-4716-bbc8-f107ad175da1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPaymentFavoriteTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57581724-1579-47b2-a2f5-46b723071b72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>588f3769-4406-460d-b03c-7da6a9e60a85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62f12709-5026-4bd0-b28e-bb2e6ac400ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Others/ticketing_buyKLIATicket</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0afdc9a6-8555-4397-bedb-f411b33e2d20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_createTabungCreatorOnly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e761e0b0-8a99-4ad3-8003-275981f3f97d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee521495-5f3d-4b6a-8f7a-53aaa0d3b0a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a38c9de-7c48-4941-9822-039ecad2ef2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc2bd863-2a42-447e-8f99-0e5c8bb5edc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_fundTabungCreatorOnly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e761e0b0-8a99-4ad3-8003-275981f3f97d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee521495-5f3d-4b6a-8f7a-53aaa0d3b0a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a38c9de-7c48-4941-9822-039ecad2ef2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97866d02-5c07-4f5a-bf9e-d7b48b216eb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_withdrawTabung</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af4fd4d9-45fa-4231-b6fc-6e8b13ef9add</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2d93728-a299-476a-9f5e-3d488bbea771</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2eeb3702-0bf7-4c04-862d-2143c7a15052</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_enableESITabung</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f0ca30-9360-4321-b034-1e5082771ce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4c7df8-47c0-4ab6-a89b-50430e7a836e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc068a4b-4743-4ad9-8b23-94c36cc82b62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_disableESITabung</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dfb4ad1-5215-4c73-8721-6af299481178</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8466e57-83ea-4117-8e35-b263cfcc3960</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0de5e1b-3778-4aed-ae2b-3fb3d5d6c9ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_renameTabung</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1dbbbcd-8cb5-410b-96cd-c93aff206f54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ad7902d-d7e4-4f76-b4a8-564df4ed56d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e12419b-17e7-4b98-b2dc-55cd930f79e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tabung/tabung_removeTabung</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8cfab50-cd28-49d1-a509-10b9928f588e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4791996b-0f7e-4bac-9d1d-c8cbc2b893cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a952bf1-5b1b-4f98-8d3f-836621590268</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transfer/transfer_thirdPartyToday</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>476820e3-4c03-4fc0-9ebe-aeeb8414fe74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aafdbd5-51b9-4b5c-b6ca-ac508be29685</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>678567f2-68d5-4ccb-8045-48aa762adc3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44307849-d6c3-46d7-b543-88b2b7aa455b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73a5a66f-e4ef-437d-b825-67271d97674f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e6c6e5f-d44f-46cd-8a6c-6a8bec15ce85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00fc51cb-c2d4-4801-96e8-a4af0ce75ebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0afc303-c79b-4c5a-a572-a8c794fa0f44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92c216dc-d1ea-4efa-9c0d-e7a6b78f98cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8c59a5b-2a10-45b1-9948-c2d4ddc99ec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64636319-ce2c-4152-9225-6dd5e84e6875</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4766e966-915e-4419-973f-606ce01addd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edadadbc-5811-49b0-8a02-895b277903c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8385028c-5b14-47d4-99b4-d60812ecf9a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5297fcf7-608d-4425-a49c-e19d19805a2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Transfer/transfer_thirdPartyFuture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51b750e8-2211-41f0-a377-497de64df562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DuitNow/duitNow_recurringTransferTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf21283d-cf5f-4246-aa12-5967e8a82d34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d3896c6-4739-4c69-8a95-40e1bb57a3d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DuitNow/duitNow_addFavoriteTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>442067ab-3068-41ee-a4f7-a8da0e0129f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa9cd32-93f5-45a7-a2f7-d2e81396cb7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c3546b2-3ceb-49e1-9fdf-4a841729c58d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Settings/settings_qrRegistration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd774039-6812-4a0e-a8c6-d5e096208969</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/sendMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf21283d-cf5f-4246-aa12-5967e8a82d34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f943948-7fac-4a66-a2f5-054eb5548f2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7bbbd3e-8577-47b6-a936-6187ce3e3cd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd8c6983-608c-40ed-add7-3a74d30f6462</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney_cancelRequest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>99b9a50f-02f5-4e09-ad95-aaee6e670773</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a01ed5e-7f92-4c68-afee-60c0376820bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney_markAsPaid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>09adcd87-0b37-4fab-b2d1-04851a0599c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/sendRequestMoney_payRequestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf21283d-cf5f-4246-aa12-5967e8a82d34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b73580-ecbd-4f3b-bb9d-04d97d3ce3ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0d3d63e-ab58-4b22-8b00-7ec0df8ec65e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d023f1fe-ee62-4f6d-9dda-2ce9142dd232</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dc5ceea-a03e-4203-b3ae-7299a62ae4a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_createSplitBillComplete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3ad651e-42ec-44f8-8021-d80b480df6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a605fb0-55a8-4cc1-aef3-5c7a0f27a319</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f4eaa94-ce1c-4344-900e-4e6942d500e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_createSplitBillThreeFriends_Paid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86385472-2763-4a3e-b500-52cfa35176db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f47dd0c-73ea-4a24-bd56-826ddd4879ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_markAsPaid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bba144ab-bdbd-41a0-b4b3-1c901cfe5373</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_removePastSplitBill</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
