<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regress 1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>amirsafwan23@gmail.com;</mailRecipient>
   <numberOfRerun>7</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3129f258-4ca5-4646-b089-445534950aa1</testSuiteGuid>
   <testCaseLink>
      <guid>fed8d3ca-a42d-40ff-abcc-e9762786c0d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login Onboard/onboard_onboardIntoMAE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514189f4-0f50-4fc5-8f87-6b6e5311aa3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d62a261-211f-48ea-9b7d-0b01f111d556</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bbd9f35-2813-43f6-bcca-f2cf98ee1c02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Settings/settings_secure2uRegistration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc5f1bf-e970-49a6-9ead-df2e6654e9b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4086c6f-0969-41d1-b6d2-60ed56e51b9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PayBill/payBills_todayTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>954e9679-7496-4767-9a60-b36be9225ce1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PayBill/payBills_Future Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78ac2c2b-5215-44c4-98c7-189d7c7fc4e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PayBill/payBills_addFavoriteTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52d9a346-d692-4f6b-bd80-b97ffa138eac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PayBill/payBills_favoriteTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6384ac72-9f18-4aa7-ab44-328062389bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d46db514-a7eb-496a-8db6-f02ddac6a7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad8a4704-7d27-4763-a241-4bbbc75f2f75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ca60f2-a174-41e1-ab95-142b9c5ea1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3c574-2e1d-4033-9aea-dd34a1a38e4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a21bb07-2d03-47ea-8dff-46b159257b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142f9b06-6481-480c-9370-09361906b7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fee83a3-ac50-4d77-b5ef-03a265e420b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de1678c0-b44e-4863-bdc5-d4f8bd192af4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_todayTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d30065c-b90f-4a7d-b953-bb741d29675a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>031d3bff-0913-4a21-8135-d5499122af4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10918dec-a2f0-4804-8daf-b5058185b249</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_Future Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb186dac-eee1-40a4-ac6f-f6a665d21e7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85768c90-7b48-42d3-b18c-4783961a788b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1acc0610-cdba-49ae-a83e-df3c934ef4d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Add Favorite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e69ad54-bb85-4350-a6fe-d116ee6bd61e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Favorite Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0cc8b16-128d-42aa-9f1a-24adfd0bef6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ca9d1b-9824-4a5b-8c6d-2dc34c246ae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c006ba5-0b9c-47a7-9f51-c87e0e5eb968</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8376c142-81a5-4230-a5b2-31ed10737797</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPaymentAddFavorite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e92331a-446b-46a7-811f-ce65d357bda6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9f0f880-3cf9-4bfb-b689-bba6176de99f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55985926-eb18-4e0f-9c5c-6b5786368d89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Zakat/zakat_zakatPaymentFavoriteTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57581724-1579-47b2-a2f5-46b723071b72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>588f3769-4406-460d-b03c-7da6a9e60a85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
