<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regress 4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>amirsafwan23@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7de6f7ca-58e3-4c2b-828d-55ce37a9b217</testSuiteGuid>
   <testCaseLink>
      <guid>07c79be0-1f78-410e-b29c-8e49e8f6e36d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Request Money/sendMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf21283d-cf5f-4246-aa12-5967e8a82d34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f943948-7fac-4a66-a2f5-054eb5548f2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10ccafe2-705f-4ae3-84ef-2559b528b6aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>922dc42b-1885-4040-a388-55a623eea277</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney_cancelRequest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>453ae6b1-4127-4086-892f-f9f4d2ca3447</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50b733d2-f9fc-410f-9119-33b03eb108ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Send Request Money/requestMoney_markAsPaid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>428cbc29-f4b4-46e4-a288-4ef1099c8ab2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Send Request Money/sendRequestMoney_payRequestMoney</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf21283d-cf5f-4246-aa12-5967e8a82d34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b73580-ecbd-4f3b-bb9d-04d97d3ce3ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0d3d63e-ab58-4b22-8b00-7ec0df8ec65e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d023f1fe-ee62-4f6d-9dda-2ce9142dd232</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb53a72d-f584-4dd4-849e-63113143df2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_createSplitBillComplete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3ad651e-42ec-44f8-8021-d80b480df6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a605fb0-55a8-4cc1-aef3-5c7a0f27a319</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baf8e161-7263-4ddf-a8f3-f1e9b9888bff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_createSplitBillThreeFriends_Paid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1e138ee-9fb6-43c8-9a22-b587b3e537e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86385472-2763-4a3e-b500-52cfa35176db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f87ebe3e-7283-4390-a7e8-037530827073</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_markAsPaid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a6562cb4-067c-4514-b596-f7f13313d435</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Split Bill/splitBill_removePastSplitBill</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
