<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JomPay</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a9064f8d-a741-4120-8e0b-59b5a9d490fc</testSuiteGuid>
   <testCaseLink>
      <guid>528b15c7-14c6-4a83-afe7-e2beefc1935e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Add Favorite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfd42430-b1e1-45a8-b9a6-65ac92b2a1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae65bcef-724d-4206-a1a9-2d1cc7dc2d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3321feb7-1bc4-45a9-9827-eefef5fec748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/JomPay Favorite Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0cc8b16-128d-42aa-9f1a-24adfd0bef6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ca9d1b-9824-4a5b-8c6d-2dc34c246ae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94dae559-cbc9-40c1-bb2b-3e9c42057351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515724ef-495a-4f6c-b1f5-74db3c20914f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f515955-815d-4839-9164-9522720ceb6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_Future Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb186dac-eee1-40a4-ac6f-f6a665d21e7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85768c90-7b48-42d3-b18c-4783961a788b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49b86edb-7fca-4b2e-a211-7cf47cb75644</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JomPay/jomPay_todayTransaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d30065c-b90f-4a7d-b953-bb741d29675a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>031d3bff-0913-4a21-8135-d5499122af4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
